=== KZGenki/ist2021/proizvodi.dtd
<!ELEMENT Proizvodi (Proizvod*)>
<!ELEMENT Proizvod (cena, tekst, tagovi, akcije)>
<!ELEMENT cena (#PCDATA)>
<!ELEMENT tekst (#PCDATA)>
<!ELEMENT tagovi (tag+)>
<!ELEMENT akcije (akcija*)>
<!ELEMENT tag (#PCDATA)>
<!ELEMENT akcija EMPTY>
<!ATTLIST Proizvodi
    xmlns:xsi CDATA #REQUIRED
    xsi:noNamespaceSchemaLocation CDATA #REQUIRED>
<!ATTLIST Proizvod kategorija (laptopovi|monitori|stolovi|stolice) #REQUIRED>
<!ATTLIST cena valuta (rsd|eur) "rsd">
<!ATTLIST akcija 
    cena CDATA #REQUIRED
    datum CDATA #REQUIRED>

=== KZGenki/ist2021/proizvodi.xml
<!DOCTYPE Proizvodi SYSTEM "proizvodi.dtd">
<Proizvodi>
    <Proizvod kategorija="laptopovi">
        <cena>
            67000
        </cena>
        <tekst>
            Neki tekst oglasa za laptop u vrednosti od 67000 dinara
        </tekst>
        <tagovi>
            <tag>Racunar</tag>
            <tag>Office</tag>
            <tag>Windows</tag>
        </tagovi>
        <akcije>
            <akcija cena="57000" datum="2020-04-29"/>
        </akcije>
    </Proizvod>
    <Proizvod kategorija="monitori">
        <cena valuta="eur">
            550
        </cena>
        <tekst>
            Neki tekst oglasa za monitor u vrednosti od 67000 dinara
        </tekst>
        <tagovi>
            <tag>Racunar</tag>
            <tag>Office</tag>
        </tagovi>
        <akcije>
            <akcija cena="500" datum="2020-05-11"/>
        </akcije>
    </Proizvod>
</Proizvodi>
